name: github

on: push

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.UNLIMITED_RICE_PUDDING }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          strategy: patch
          bump_version_scheme: patch
